services:
  mmmm-react-blue:
    image: react-image:latest
    container_name: react
    ports:
      - "3000:80"
    environment:
      TZ: "Asia/Seoul"
    networks:
      - app-network
networks:
  app-network:
    external: true
