data:
  ratio: 0.7
  image_size: 224
---
train:
  batch_size: 16
  num_workers: 8
  epochs: 100
  optimizer: "Adam"
  lr: 0.001
  epsilon: 1.0
---
log:
  project_name: "deepfake-disrupter-box-landmarks-multiple-v2"
  chkpt: "./checkpoints"
